'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Hero from "@/components/Navbar/page";
import { usePathname } from "next/navigation";
import { Metadata } from "next";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();  // Ambil path saat ini
  const disableNavbar = ["/input", "/Inp",
  "/Inp/galley"
  ];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {!disableNavbar.includes(pathname) && <Hero />}
        {children}
      </body>
    </html>
  );
}
